qmlfileio: add missing include
| ../git/src/qmlfileio.cpp:20:29: error: expected constructor, destructor, or type conversion before '(' token
|    Q_COREAPP_STARTUP_FUNCTION(registerTypes)
|                              ^

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>