qmlfileio: add missing include
|  class QDebug;
|        ^~~~~~
| ../git/src/qmlfileio.cpp:189:14: error: invalid use of incomplete type 'class QDebug'
|      qWarning() << "QmlFileIO: File can not be read:" << t_file.fileName();

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>